package org.example.common;

public abstract class PropertiesNames {
    public static final String EMAIL_SENDER_ADDRESS_PROP = "mail.sender.noreply.address";
    public static final String EMAIL_SENDER_EXTERNAL_PASSWORD_PROP = "mail.sender.noreply.external.password";
    public static final String EMAIL_RECIPIENT_ADDRESS_PROP = "mail.sender.noreply.recipient";
    public static final String REPORT_GROUPS_TO_PROCESS_PROP = "report.groups-to-process";
    public static final String TASK_COLLECT_SECURITY_INFO_DELAY_SECONDS_PROP = "task.collect.security.group.delay.seconds";
    public static final String TASK_COLLECT_SECURITY_INFO_PERIOD_SECONDS_PROP = "task.collect.security.group.period.seconds";
    public static final String TASK_COLLECT_APPLICATION_INFO_DELAY_SECONDS_PROP = "task.collect.application.group.delay.seconds";
    public static final String TASK_COLLECT_APPLICATION_INFO_PERIOD_SECONDS_PROP = "task.collect.application.group.period.seconds";
    public static final String TASK_COLLECT_BC_INFO_DELAY_SECONDS_PROP = "task.collect.branch-cache.group.delay.seconds";
    public static final String TASK_COLLECT_BC_INFO_PERIOD_SECONDS_PROP = "task.collect.branch-cache.group.period.seconds";
    public static final String TASK_COLLECT_COMMON_INFO_DELAY_SECONDS_PROP = "task.collect.common-info.group.delay.seconds";
    public static final String TASK_COLLECT_COMMON_INFO_PERIOD_SECONDS_PROP = "task.collect.common-info.group.period.seconds";
    public static final String TASK_COLLECT_DIRECT_ACCESS_INFO_DELAY_SECONDS_PROP = "task.collect.direct-access.group.delay.seconds";
    public static final String TASK_COLLECT_DIRECT_ACCESS_INFO_PERIOD_SECONDS_PROP = "task.collect.direct-access.group.period.seconds";
    public static final String TASK_COLLECT_STORAGE_INFO_DELAY_SECONDS_PROP = "task.collect.storage.group.delay.seconds";
    public static final String TASK_COLLECT_STORAGE_INFO_PERIOD_SECONDS_PROP = "task.collect.storage.group.period.seconds";
    public static final String TASK_COLLECT_DNS_CLIENT_INFO_DELAY_SECONDS_PROP = "task.collect.dns-client.group.delay.seconds";
    public static final String TASK_COLLECT_DNS_CLIENT_INFO_PERIOD_SECONDS_PROP = "task.collect.dns-client.group.period.seconds";
    public static final String TASK_COLLECT_EVENT_LOG_INFO_DELAY_SECONDS_PROP = "task.collect.event-log.group.delay.seconds";
    public static final String TASK_COLLECT_EVENT_LOG_INFO_PERIOD_SECONDS_PROP = "task.collect.event-log.group.period.seconds";
    public static final String TASK_COLLECT_NETWORK_INFO_DELAY_SECONDS_PROP = "task.collect.network.group.delay.seconds";
    public static final String TASK_COLLECT_NETWORK_INFO_PERIOD_SECONDS_PROP = "task.collect.network.group.period.seconds";
    public static final String TASK_COLLECT_SYSTEM_INFO_DELAY_SECONDS_PROP = "task.collect.system-info.group.delay.seconds";
    public static final String TASK_COLLECT_SYSTEM_INFO_PERIOD_SECONDS_PROP = "task.collect.system-info.group.period.seconds";
    public static final String TASK_COLLECT_PNP_DEVICES_INFO_DELAY_SECONDS_PROP = "task.collect.pnp-device.group.delay.seconds";
    public static final String TASK_COLLECT_PNP_DEVICES_INFO_PERIOD_SECONDS_PROP = "task.collect.pnp-device.group.period.seconds";
    public static final String TASK_COLLECT_PRINT_MANAGEMENT_INFO_DELAY_SECONDS_PROP = "task.collect.print-management.group.delay.seconds";
    public static final String TASK_COLLECT_PRINT_MANAGEMENT_INFO_PERIOD_SECONDS_PROP = "task.collect.print-management.group.period.seconds";
    public static final String TASK_COLLECT_REALTIME_MANAGEMENT_INFO_DELAY_SECONDS_PROP = "task.collect.realtime-management.group.delay.seconds";
    public static final String TASK_COLLECT_REALTIME_MANAGEMENT_INFO_PERIOD_SECONDS_PROP = "task.collect.realtime-management.group.period.seconds";
    public static final String TASK_COLLECT_WMI_OBJECTS_INFO_DELAY_SECONDS_PROP = "task.collect.wmi-objects.group.delay.seconds";
    public static final String TASK_COLLECT_WMI_OBJECTS_INFO_PERIOD_SECONDS_PROP = "task.collect.wmi-objects.group.period.seconds";
    public static final String TASK_COLLECT_AUDIO_INFO_DELAY_SECONDS_PROP = "task.collect.audio.group.delay.seconds";
    public static final String TASK_COLLECT_AUDIO_INFO_PERIOD_SECONDS_PROP = "task.collect.audio.group.period.seconds";
    public static final String TASK_COLLECT_AUDIO_DURATION_SECONDS_PROP = "task.collect.audio.duration.seconds";
    public static final String TASK_COLLECT_VIDEO_INFO_DELAY_SECONDS_PROP = "task.collect.video.group.delay.seconds";
    public static final String TASK_COLLECT_VIDEO_INFO_PERIOD_SECONDS_PROP = "task.collect.video.group.period.seconds";
    public static final String TASK_COLLECT_VIDEO_DURATION_SECONDS_PROP = "task.collect.video.duration.seconds";
    public static final String TASK_COLLECT_VIDEO_DELAY_BETWEEN_IMAGES_PROP = "task.collect.video.delay-between-images.millis";
}
